name: Java Maven CI/CD Pipeline

on:
  push:
    branches:
      - main
      - AI-CR-Testing

jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install --upgrade openai

      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_code_review.py

      - name: Upload Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-reports
          path: ./reports

  ai_test_generation:
    needs: ai_code_review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install openai pytest

      - name: Ensure Test Directory Exists
        run: mkdir -p src/test/java/  # Make sure the directory is created

      - name: Generate AI-Based Unit Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_test_generator.py

      - name: Verify Test Files Exist
        run: ls -la src/test/java/

      - name: Upload Tests as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-tests
          path: src/test/java  # Ensure tests are uploaded for the next job

  security_scan:
    needs: ai_test_generation  # Ensure this job runs after ai_test_generation job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Check Snyk Version
        run: snyk --version  # Check the installed version of Snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      - name: Install Maven dependencies
        run: mvn install  # Ensure dependencies are downloaded

      - name: Run Snyk Security Scan (No Pipeline Failure)
        run: snyk test --json > snyk-report.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}

      - name: Upload Snyk Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

  ai_security_scan_analysis:
    needs: security_scan  # Ensure this job runs after the security_scan job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install openai

      # Download and unzip the snyk report artifact
      - name: Download Snyk Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: snyk-report
          path: ./snyk-report


      - name: Run AI Security Scan Analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_security_scan.py ./snyk-report/snyk-report.json

      - name: Upload AI Security Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: ai-security-report
          path: ./ai_security_report.json

  build_and_test:
    needs: [ai_test_generation, security_scan, ai_security_scan_analysis]  # Ensure this job runs after the other jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Generated Tests
        uses: actions/download-artifact@v4  # Download the artifact created in ai_test_generation
        with:
          name: generated-tests
          path: src/test/java  # Download to the same path

      - name: Download Snyk Report
        uses: actions/download-artifact@v4
        with:
          name: snyk-report
          path: ./snyk-report/snyk-report.json  # Corrected path

      - name: Download AI Security Report
        uses: actions/download-artifact@v4
        with:
          name: ai-security-report
          path: ai_security_report.json  # Download the AI security analysis report

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/*.jar
