name: Java Maven CI/CD Pipeline

on:
  push:
    branches:
      - main
      - AI-CR-Testing

jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install --upgrade openai

      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_code_review.py

      - name: Upload Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-reports
          path: ./reports

      - name: Send Teams Notification for Approval
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "🚀 *Manual Approval Needed* 🚀\n\nAI Code Review is complete. Please review and approve to continue.\n\n🔗 [GitHub Actions Run](https://github.com/YOUR_REPO/actions/runs)"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}

  manual_approval:
    needs: ai_code_review
    runs-on: ubuntu-latest
    environment: manual-approval-required  # Enforce manual approval via GitHub Environments
    steps:
      - name: Pause for Manual Review
        run: echo "Waiting for manual approval in GitHub UI..."

  ai_test_generation:
    needs: manual_approval  # Requires manual approval first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install openai pytest

      - name: Ensure Test Directory Exists
        run: mkdir -p src/test/java/  # Make sure the directory is created

      - name: Generate AI-Based Unit Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_test_generator.py

      - name: Verify Test Files Exist
        run: ls -la src/test/java/

      - name: Upload Tests as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-tests
          path: src/test/java  # Ensure tests are uploaded for the next job

  build_and_test:
    needs: ai_test_generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Generated Tests
        uses: actions/download-artifact@v4  # Download the artifact created in ai_test_generation
        with:
          name: generated-tests
          path: src/test/java  # Download to the same path

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/*.jar
